version: "3.1"

services:
  db:
    image: postgres
    container_name: pp-db
    restart: unless-stopped
    # volumes:
    #   - ./backend/docker-data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  adminer:
    depends_on: [db]
    image: adminer
    container_name: pp-adminer
    restart: unless-stopped
    ports:
      - 8090:8080

  api:
    container_name: pp-api
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: always
    env_file:
      - "./backend/.env"
    volumes:
      - /app/node_modules
      - ./backend:/app/
    depends_on:
      - db
    ports:
      - 3001:3001

  frontend:
    container_name: pp-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /app/frontend/node_modules
      - ./frontend:/app/frontend
    environment:
      SHELL: "/bin/sh"
    depends_on:
      - api
    ports:
      - 8080:8080
